## Site metadata ##

title: Chris Zingels Site
description: Some musing

### Built settings ###

url: "https://chriszingel.github.io"
baseurl: "/zingtech"

github_username: chrisZingel

theme: minima
